#############################################################################
# Makefile for building: kantalupe_edit
# Generated by qmake (2.01a) (Qt 4.7.0) on: Di 19. Apr 17:31:26 2011
# Project:  kantalupe_edit.pro
# Template: app
# Command: e:\coding\qt\4.7.0\mingw\qt\bin\qmake.exe -spec e:\coding\qt\4.7.0\mingw\qt\mkspecs\win32-g++ CONFIG+=release QMLJSDEBUGGER_PATH=E:/coding/Qt/creator_2.1/share/qtcreator/qml/qmljsdebugger QMLJSDEBUGGER_PATH=E:/coding/Qt/creator_2.1/share/qtcreator/qml/qmljsdebugger -o Makefile kantalupe_edit.pro
#############################################################################

first: release
install: release-install
uninstall: release-uninstall
MAKEFILE      = Makefile
QMAKE         = e:\coding\qt\4.7.0\mingw\qt\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = move
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
SUBTARGETS    =  \
		release \
		debug

release: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_default: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-make_first: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release first
release-all: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_default: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-make_first: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug first
debug-all: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: kantalupe_edit.pro  e:/coding/qt/4.7.0/mingw/qt/mkspecs/win32-g++/qmake.conf e:/coding/Qt/4.7.0/mingw/qt/mkspecs/qconfig.pri \
		e:/coding/Qt/4.7.0/mingw/qt/mkspecs/modules/qt_webkit_version.pri \
		e:/coding/qt/4.7.0/mingw/qt/mkspecs/features/qt_functions.prf \
		e:/coding/qt/4.7.0/mingw/qt/mkspecs/features/qt_config.prf \
		e:/coding/qt/4.7.0/mingw/qt/mkspecs/features/exclusive_builds.prf \
		e:/coding/qt/4.7.0/mingw/qt/mkspecs/features/default_pre.prf \
		e:/coding/qt/4.7.0/mingw/qt/mkspecs/features/win32/default_pre.prf \
		e:/coding/qt/4.7.0/mingw/qt/mkspecs/features/release.prf \
		e:/coding/qt/4.7.0/mingw/qt/mkspecs/features/debug_and_release.prf \
		e:/coding/qt/4.7.0/mingw/qt/mkspecs/features/default_post.prf \
		e:/coding/qt/4.7.0/mingw/qt/mkspecs/features/win32/default_post.prf \
		e:/coding/qt/4.7.0/mingw/qt/mkspecs/features/qt.prf \
		e:/coding/qt/4.7.0/mingw/qt/mkspecs/features/win32/thread.prf \
		e:/coding/qt/4.7.0/mingw/qt/mkspecs/features/moc.prf \
		e:/coding/qt/4.7.0/mingw/qt/mkspecs/features/win32/rtti.prf \
		e:/coding/qt/4.7.0/mingw/qt/mkspecs/features/win32/exceptions.prf \
		e:/coding/qt/4.7.0/mingw/qt/mkspecs/features/win32/stl.prf \
		e:/coding/qt/4.7.0/mingw/qt/mkspecs/features/shared.prf \
		e:/coding/qt/4.7.0/mingw/qt/mkspecs/features/warn_on.prf \
		e:/coding/qt/4.7.0/mingw/qt/mkspecs/features/win32/windows.prf \
		e:/coding/qt/4.7.0/mingw/qt/mkspecs/features/resources.prf \
		e:/coding/qt/4.7.0/mingw/qt/mkspecs/features/uic.prf \
		e:/coding/qt/4.7.0/mingw/qt/mkspecs/features/yacc.prf \
		e:/coding/qt/4.7.0/mingw/qt/mkspecs/features/lex.prf \
		e:/coding/qt/4.7.0/mingw/qt/mkspecs/features/include_source_dir.prf \
		e:/coding/Qt/4.7.0/mingw/qt/lib/qtmain.prl
	$(QMAKE) -spec e:\coding\qt\4.7.0\mingw\qt\mkspecs\win32-g++ CONFIG+=release QMLJSDEBUGGER_PATH=E:/coding/Qt/creator_2.1/share/qtcreator/qml/qmljsdebugger QMLJSDEBUGGER_PATH=E:/coding/Qt/creator_2.1/share/qtcreator/qml/qmljsdebugger -o Makefile kantalupe_edit.pro
e:\coding\Qt\4.7.0\mingw\qt\mkspecs\qconfig.pri:
e:\coding\Qt\4.7.0\mingw\qt\mkspecs\modules\qt_webkit_version.pri:
e:\coding\qt\4.7.0\mingw\qt\mkspecs\features\qt_functions.prf:
e:\coding\qt\4.7.0\mingw\qt\mkspecs\features\qt_config.prf:
e:\coding\qt\4.7.0\mingw\qt\mkspecs\features\exclusive_builds.prf:
e:\coding\qt\4.7.0\mingw\qt\mkspecs\features\default_pre.prf:
e:\coding\qt\4.7.0\mingw\qt\mkspecs\features\win32\default_pre.prf:
e:\coding\qt\4.7.0\mingw\qt\mkspecs\features\release.prf:
e:\coding\qt\4.7.0\mingw\qt\mkspecs\features\debug_and_release.prf:
e:\coding\qt\4.7.0\mingw\qt\mkspecs\features\default_post.prf:
e:\coding\qt\4.7.0\mingw\qt\mkspecs\features\win32\default_post.prf:
e:\coding\qt\4.7.0\mingw\qt\mkspecs\features\qt.prf:
e:\coding\qt\4.7.0\mingw\qt\mkspecs\features\win32\thread.prf:
e:\coding\qt\4.7.0\mingw\qt\mkspecs\features\moc.prf:
e:\coding\qt\4.7.0\mingw\qt\mkspecs\features\win32\rtti.prf:
e:\coding\qt\4.7.0\mingw\qt\mkspecs\features\win32\exceptions.prf:
e:\coding\qt\4.7.0\mingw\qt\mkspecs\features\win32\stl.prf:
e:\coding\qt\4.7.0\mingw\qt\mkspecs\features\shared.prf:
e:\coding\qt\4.7.0\mingw\qt\mkspecs\features\warn_on.prf:
e:\coding\qt\4.7.0\mingw\qt\mkspecs\features\win32\windows.prf:
e:\coding\qt\4.7.0\mingw\qt\mkspecs\features\resources.prf:
e:\coding\qt\4.7.0\mingw\qt\mkspecs\features\uic.prf:
e:\coding\qt\4.7.0\mingw\qt\mkspecs\features\yacc.prf:
e:\coding\qt\4.7.0\mingw\qt\mkspecs\features\lex.prf:
e:\coding\qt\4.7.0\mingw\qt\mkspecs\features\include_source_dir.prf:
e:\coding\Qt\4.7.0\mingw\qt\lib\qtmain.prl:
qmake: qmake_all FORCE
	@$(QMAKE) -spec e:\coding\qt\4.7.0\mingw\qt\mkspecs\win32-g++ CONFIG+=release QMLJSDEBUGGER_PATH=E:/coding/Qt/creator_2.1/share/qtcreator/qml/qmljsdebugger QMLJSDEBUGGER_PATH=E:/coding/Qt/creator_2.1/share/qtcreator/qml/qmljsdebugger -o Makefile kantalupe_edit.pro

qmake_all: FORCE

make_default: release-make_default debug-make_default FORCE
make_first: release-make_first debug-make_first FORCE
all: release-all debug-all FORCE
clean: release-clean debug-clean FORCE
distclean: release-distclean debug-distclean FORCE
	-$(DEL_FILE) Makefile

check: first

release-mocclean: $(MAKEFILE).Release
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean: $(MAKEFILE).Debug
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables: $(MAKEFILE).Release
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables: $(MAKEFILE).Debug
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
