#ifndef PLUGIN_EXPORT_SMSSURVEY_GLOBAL_H
#define PLUGIN_EXPORT_SMSSURVEY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PLUGIN_EXPORT_SMSSURVEY_LIBRARY)
#  define PLUGIN_EXPORT_SMSSURVEYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PLUGIN_EXPORT_SMSSURVEYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PLUGIN_EXPORT_SMSSURVEY_GLOBAL_H
