#ifndef PLUGIN_EXPORT_LIMESURVEY_GLOBAL_H
#define PLUGIN_EXPORT_LIMESURVEY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PLUGIN_EXPORT_LIMESURVEY_LIBRARY)
#  define PLUGIN_EXPORT_LIMESURVEYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PLUGIN_EXPORT_LIMESURVEYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PLUGIN_EXPORT_LIMESURVEY_GLOBAL_H
